# Generated by Django 4.2.7 on 2023-12-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
